### ISSUE TITLE
对话依赖关系提取

### ISSUE THREAD

**Issue by littlehacker26** [JiaQiSJTU/ResponseSelection#1]
想问一下这份代码包含对话关系提取的模型训练吗，我实在没找到相关内容。谢谢！

**Comment by JiaQiSJTU** [comment]
这份代码里目前没有包含。对话关系提取的模型是来源于2019AAAI的一篇文章《A Deep Sequential Model for Discourse Parsing on Multi-Party Dialogues》，它的代码位于：https://github.com/shizhouxing/DialogueDiscourseParsing。

**Comment by JiaQiSJTU** [comment]
该模型用于本文的训练数据来自论文：A large-scale corpus for conversation disentanglement。我们对该数据集进行了处理（详情见paper），后续也会将处理后的数据集等相关内容整合进来。谢谢！
