### ISSUE TITLE
How to install mkl-* libraries?

### ISSUE THREAD

**Issue by chijames** [JiaQiSJTU/ResponseSelection#2]
Hi,

Thanks for releasing the code. However, I follow the step in readme and it keeps saying "ERROR: Could not find a version that satisfies the requirement mkl-fft==1.0.15".

**Comment by JiaQiSJTU** [comment]
These libraries under corresponding versions are installed when I install python3.7 and torch1.1 with conda at that time.  I guess the other versions is also ok.
