### ISSUE TITLE
Do I need to install parlai?

### ISSUE THREAD

**Issue by chijames** [JiaQiSJTU/ResponseSelection#3]
This might be a silly question, but do I need to install parlai in order to run the code in this repo? Since I see some import statements such as "from parlai.scripts import build_dict" here and there. If so, what version should I install?

**Comment by JiaQiSJTU** [comment]
It's a good question. No, you don't need to install the original parlai. All of the related codes needed from parlai are included under this repository.

**Comment by chijames** [comment]
Thanks for the reply!

However, some lines in the file, for example, https://github.com/JiaQiSJTU/ResponseSelection/blob/master/parlai/scripts/train_model.py#L37,
seems to need original parlai files? I cannot find a file name build_dict.py under script/

**Comment by JiaQiSJTU** [comment]
Sincerely apologize for the missing files. The original codes is also added in the Readme. Thanks a lot! ! !
