### ISSUE TITLE
How to reproduce results on dstc8

### ISSUE THREAD

**Issue by chijames** [JiaQiSJTU/ResponseSelection#4]
Hi,

I would like to reproduce results on dstc8 dataset. Can you show me how to do so? Thanks a lot!

**Comment by JiaQiSJTU** [comment]
1.  Download the original DSTC8 subtask 2 dataset and remove the samples without correct responses.
2. Train a discourse parsing model with the dataset and code in README.
3. Parse the DSTC8* dataset and reformat it as the DSTC7 dataset.
4. Add a new task in ParlAI and train with this new task.
