### ISSUE TITLE
项目运行出现警告

### ISSUE THREAD

**Issue by qingyue2014** [JiaQiSJTU/ResponseSelection#5]
您好，我按照readme文件逐步运行代码，出现了两个警告：
1. [ WARNING ] : your model is being loaded with opts that do not exist in the model you are initializing the weights with *****
2. [ WARNING ] : your model is being loaded with opts that differ from the model you are initializing the weights with. Add the following args to your run command to change this: *****
这两个警告是什么意思呢？我忽略了这两个警告，继续运行模型，在迭代若干轮发现hits@1在dstc7数据集上只有不到60，与论文中报告的73.3还有一定距离，请问是否与警告有关系呢？

**Comment by JiaQiSJTU** [comment]
和警告无关。我查看了当初训练的log，是在训练13个epoch后out of patience自动结束训练的。

**Comment by JiaQiSJTU** [comment]
可能是参数和readme中有些出入：batchsize=128

**Comment by JiaQiSJTU** [comment]
可能readme中batchsize等参数有些出入：batchsize=128

**Comment by qingyue2014** [comment]
您好，我按照github项目上的readme设置参数（仍旧保持batch_size=32），经过8个epoch在dstc7上达到了论文中的分数，没有问题，非常感谢您的回复！
